export const ONBOARDING_IPC_CHANNELS = {
  status: "onboarding:get-status",
  complete: "onboarding:complete",
  checkCodex: "onboarding:check-codex",
  copyInstallCommand: "onboarding:copy-install-command",
  cliReadinessState: "onboarding:cli-readiness:state",
  cliReadinessCheck: "onboarding:cli-readiness:check",
  cliInstallState: "onboarding:cli-install:state",
  cliInstallStart: "onboarding:cli-install:start",
  claudeUpdateStart: "onboarding:claude-update:start",
  cliInstallCancel: "onboarding:cli-install:cancel",
  cliInstallSnapshot: "onboarding:cli-install:snapshot",
  teamBuilderState: "onboarding:team-builder:state",
  teamBuilderStart: "onboarding:team-builder:start",
  teamBuilderSubmit: "onboarding:team-builder:submit",
  teamBuilderAdjust: "onboarding:team-builder:adjust",
  teamBuilderRetry: "onboarding:team-builder:retry",
  teamBuilderCommit: "onboarding:team-builder:commit",
} as const;
