import type { ArchitectureLayerAssignment, FourLayerArchitectureConfig } from "./import-boundaries.js";

const exact = (layer: ArchitectureLayerAssignment["layer"], paths: readonly string[]): ArchitectureLayerAssignment[] =>
  paths.map((value) => ({ layer, scope: { kind: "exact", value } }));

export const FOUR_LAYER_BOUNDARY_RULE_IDS = [
  "architecture-layer-assignment-total",
  "architecture-layer-dependency-matrix",
  "domain-pure-runtime-closure",
  "view-no-side-effect-adapters",
  "application-no-view-dependency",
  "adapter-no-use-case-reentry",
  "composition-root-narrow-allowlist",
  "application-use-case-shape",
  "adapter-boundary-branch-total",
] as const;

export const FOUR_LAYER_VIEW_FILES = [
  "packages/console-ui/src/ai-team-builder/team-builder-view.tsx",
  "packages/console-ui/src/ai-team-builder/team-proposal-card.tsx",
  "packages/console-ui/src/brand/moebius-logo.tsx",
  "packages/console-ui/src/console/accept-card.tsx",
  "packages/console-ui/src/console/agent-initial-avatar.tsx",
  "packages/console-ui/src/console/agent-markdown-mention-editor.tsx",
  "packages/console-ui/src/console/agent-message.tsx",
  "packages/console-ui/src/console/agent-team-detail.tsx",
  "packages/console-ui/src/console/agent-teams-page.tsx",
  "packages/console-ui/src/console/analysis-panel.tsx",
  "packages/console-ui/src/console/change-tab.tsx",
  "packages/console-ui/src/console/composer-context.tsx",
  "packages/console-ui/src/console/conversation-empty-state.tsx",
  "packages/console-ui/src/console/conversation-layout.ts",
  "packages/console-ui/src/console/conversation-relay-rail-model.ts",
  "packages/console-ui/src/console/conversation-relay-rail.tsx",
  "packages/console-ui/src/console/conversation-search.tsx",
  "packages/console-ui/src/console/conversation-sidebar.tsx",
  "packages/console-ui/src/console/execution-profile-registry.ts",
  "packages/console-ui/src/console/file-diff-view.tsx",
  "packages/console-ui/src/console/file-reference-tab.tsx",
  "packages/console-ui/src/console/markdown-internal-reference.ts",
  "packages/console-ui/src/console/markdown-message.tsx",
  "packages/console-ui/src/console/member-name.ts",
  "packages/console-ui/src/console/new-conversation-page.tsx",
  "packages/console-ui/src/console/operator-console.tsx",
  "packages/console-ui/src/console/process-event.tsx",
  "packages/console-ui/src/console/process-scroll-model.ts",
  "packages/console-ui/src/console/process-tab.tsx",
  "packages/console-ui/src/console/project-files-tab.tsx",
  "packages/console-ui/src/console/result-card.tsx",
  "packages/console-ui/src/console/right-sidebar-tabs.ts",
  "packages/console-ui/src/console/right-sidebar.tsx",
  "packages/console-ui/src/console/role-composer.tsx",
  "packages/console-ui/src/console/role-tag.tsx",
  "packages/console-ui/src/console/run-block.tsx",
  "packages/console-ui/src/console/run-outcome.tsx",
  "packages/console-ui/src/console/run-time.tsx",
  "packages/console-ui/src/console/session-context-header.tsx",
  "packages/console-ui/src/console/session-team-menu.tsx",
  "packages/console-ui/src/console/settings-dialog.tsx",
  "packages/console-ui/src/console/status-dot.ts",
  "packages/console-ui/src/console/structured-attachments.tsx",
  "packages/console-ui/src/console/sub-session-card.tsx",
  "packages/console-ui/src/console/sub-session-panel.tsx",
  "packages/console-ui/src/console/subtask-tab.tsx",
  "packages/console-ui/src/console/team-selection-label.ts",
  "packages/console-ui/src/console/text-fragment-list.tsx",
  "packages/console-ui/src/i18n/index.tsx",
  "packages/console-ui/src/i18n/locales/console.en.ts",
  "packages/console-ui/src/i18n/locales/console.zh-CN.ts",
  "packages/console-ui/src/i18n/locales/en.ts",
  "packages/console-ui/src/i18n/locales/zh-CN.ts",
  "packages/console-ui/src/i18n/resources.ts",
  "packages/console-ui/src/index.ts",
  "packages/console-ui/src/lib/utils.ts",
  "packages/console-ui/src/onboarding/onboarding-shell.tsx",
  "packages/console-ui/src/onboarding/onboarding-state.ts",
  "packages/console-ui/src/onboarding/relay-demo/relay-demo.tsx",
  "packages/console-ui/src/onboarding/relay-demo/relay-geometry.ts",
  "packages/console-ui/src/onboarding/relay-demo/relay-graph.tsx",
  "packages/console-ui/src/onboarding/relay-demo/relay-messages.tsx",
  "packages/console-ui/src/onboarding/relay-demo/relay-motion.ts",
  "packages/console-ui/src/onboarding/relay-demo/relay-replay-button.tsx",
  "packages/console-ui/src/style-entry.ts",
  "packages/console-ui/src/ui/avatar.tsx",
  "packages/console-ui/src/ui/badge.tsx",
  "packages/console-ui/src/ui/button.tsx",
  "packages/console-ui/src/ui/card.tsx",
  "packages/console-ui/src/ui/dropdown-menu.tsx",
  "packages/console-ui/src/ui/input.tsx",
  "packages/console-ui/src/ui/popover.tsx",
  "packages/console-ui/src/ui/tooltip.tsx",
  "src/observer/render.ts",
] as const;

export const FOUR_LAYER_APPLICATION_FILES = [
  "desktop/src/ai-team-builder/index.ts",
  "desktop/src/console-page/app.tsx",
  "desktop/src/console-page/use-managed-attachments.ts",
  "desktop/src/console-page/state-sync.ts",
  "desktop/src/main.ts",
  "desktop/src/onboarding/onboarding-route.tsx",
  "desktop/src/runner-child.ts",
  "desktop/src/runner-launch.ts",
  "desktop/src/team-onboarding-orchestration.ts",
  "src/agent-prescripts/ceo-ledger-context.ts",
  "src/agent-prescripts/current-repo-workspace.ts",
  "src/agent-prescripts/dev-workspace.ts",
  "src/agent-prescripts/index.ts",
  "src/agent-prescripts/issue-worktree.ts",
  "src/ceo-orchestration.ts",
  "src/driver-pool.ts",
  "src/issue-dispatcher.ts",
  "src/local-console/process-history.ts",
  "src/local-console/conversation-workspace-runtime.ts",
  "src/local-console/provider-invocation-flow.ts",
  "src/local-console/route-bus.ts",
  "src/local-console/runtime.ts",
  "src/local-console/session-continuation-runtime.ts",
  "src/local-console/session-presentation-runtime.ts",
  "src/local-console/state-query-runtime.ts",
  "src/local-console/run-preparation-flow.ts",
  "src/local-console/run-failure-runtime.ts",
  "src/local-console/run-lifecycle-runtime.ts",
  "src/local-console/pending-session-context-runtime.ts",
  "src/local-console/run-recovery-runtime.ts",
  "src/local-console/project-command-runtime.ts",
  "src/local-console/session-creation-runtime.ts",
  "src/local-console/session-settings-runtime.ts",
  "src/local-console/session-reference-runtime.ts",
  "src/local-console/run-terminal-flow.ts",
  "src/local-console/worker-dispatch-flow.ts",
  "src/retry.ts",
  "src/runner.ts",
  "src/runner/acceptance-prepass.ts",
  "src/runner/codex-execution-reaction.ts",
  "src/runner/external-route.ts",
  "src/runner/runtime-contracts.ts",
  "src/scanner.ts",
  "src/state-persister.ts",
] as const;

export const FOUR_LAYER_ADAPTER_FILES = [
  "desktop/src/ai-team-builder-ipc.ts",
  "desktop/src/ai-team-builder/claude-spawner.ts",
  "desktop/src/ai-team-builder/codex-spawner.ts",
  "desktop/src/ai-team-builder/kimi-spawner.ts",
  "desktop/src/ai-team-builder/team-writer.ts",
  "desktop/src/console-page/attachment-client.ts",
  "desktop/src/console-page/browser-fetch.ts",
  "desktop/src/console-page/draft-store.ts",
  "desktop/src/console-page/language-state.ts",
  "desktop/src/console-page/right-sidebar-tabs-store.ts",
  "desktop/src/console-page/settings-state.ts",
  "desktop/src/console-page/team-state.ts",
  "desktop/src/data-root.ts",
  "desktop/src/ai-team-builder/execution-profile.ts",
  "desktop/src/env-doctor.ts",
  "desktop/src/execution-capabilities.ts",
  "desktop/src/external-link.ts",
  "desktop/src/language-preference-ipc.ts",
  "desktop/src/language-preference.ts",
  "desktop/src/main-window-options.ts",
  "desktop/src/onboarding/cli-installer-manager.ts",
  "desktop/src/onboarding/first-run-marker.ts",
  "desktop/src/onboarding/cli-readiness.ts",
  "desktop/src/onboarding/ipc.ts",
  "desktop/src/preload.ts",
  "desktop/src/session-log-clipboard.ts",
  "desktop/src/settings-ipc.ts",
  "desktop/src/shell-path.ts",
  "desktop/src/team-builder-view-state.ts",
  "desktop/src/team-conversation-preference.ts",
  "desktop/src/team-external-change.ts",
  "desktop/src/team-file-manager.ts",
  "desktop/src/team-ipc.ts",
  "desktop/src/team-management-store.ts",
  "desktop/src/team-official-management.ts",
  "desktop/src/team-official-update.ts",
  "desktop/src/team-record-store.ts",
  "desktop/src/team-repair-ipc.ts",
  "desktop/src/team-runtime-binding.ts",
  "desktop/src/team-seed.ts",
  "desktop/src/team-store.ts",
  "desktop/src/updater.ts",
  "src/agent-context-state.ts",
  "src/ceo-scripts.ts",
  "src/claude-executable.ts",
  "src/claude.ts",
  "src/cli-executable.ts",
  "src/codex-rollout.ts",
  "src/codex.ts",
  "src/config.ts",
  "src/format-ceo.ts",
  "src/github-intake-state.ts",
  "src/github-state-store.ts",
  "src/github.ts",
  "src/goal-ledger-state.ts",
  "src/kimi-executable.ts",
  "src/kimi-runtime-home.ts",
  "src/kimi.ts",
  "src/local-config.ts",
  "src/local-console/attachments.ts",
  "src/local-console/child-session-summary-reader.ts",
  "src/local-console/codex-resume.ts",
  "src/local-console/codex-rollout.ts",
  "src/local-console/codex-thread-link-reader.ts",
  "src/local-console/execution-context-reader.ts",
  "src/local-console/execution-driver.ts",
  "src/local-console/file-read.ts",
  "src/local-console/output-tail.ts",
  "src/local-console/process-fact-reader.ts",
  "src/local-console/provider-process-trace.ts",
  "src/local-console/run-recovery-reader.ts",
  "src/local-console/runtime-file-support.ts",
  "src/local-console/server.ts",
  "src/local-console/session-fact-log.ts",
  "src/local-console/store.ts",
  "src/local-console/t5-store.ts",
  "src/local-console/store-timeout.ts",
  "src/local-console/workspace-diff.ts",
  "src/local-console/workspace-source.ts",
  "src/media-assets.ts",
  "src/observer/read-state.ts",
  "src/observer/server.ts",
  "src/sqlite-state-worker.ts",
  "src/sqlite-state.ts",
  "src/state.ts",
  "src/trusted-jsonl.ts",
] as const;

export const FOUR_LAYER_DOMAIN_FILES = [
  "desktop/src/ai-team-builder/contract.ts",
  "desktop/src/ai-team-builder/driver.ts",
  "desktop/src/ai-team-builder/dto.ts",
  "desktop/src/ai-team-builder/instructions.ts",
  "desktop/src/ai-team-builder/output-schema.ts",
  "desktop/src/ai-team-builder/state-machine.ts",
  "desktop/src/ai-team-builder/validator.ts",
  "desktop/src/console-page/attachment-preview.ts",
  "desktop/src/console-page/conversation-reading-position.ts",
  "desktop/src/console-page/edit-resend.ts",
  "desktop/src/console-page/interrupt.ts",
  "desktop/src/console-page/new-conversation.ts",
  "desktop/src/console-page/presentation-route.ts",
  "desktop/src/console-page/right-sidebar-preference.ts",
  "desktop/src/console-page/selection-preference.ts",
  "desktop/src/console-page/sidebar-conversation-drafts.ts",
  "desktop/src/console-page/sidebar-preference.ts",
  "desktop/src/i18n/index.ts",
  "desktop/src/i18n/locales/en.ts",
  "desktop/src/i18n/locales/zh-CN.ts",
  "desktop/src/language-preference-contract.ts",
  "desktop/src/onboarding/cli-installer-contract.ts",
  "desktop/src/onboarding/cli-installer-registry.ts",
  "desktop/src/onboarding/cli-readiness-contract.ts",
  "desktop/src/onboarding/contract.ts",
  "desktop/src/onboarding/onboarding-completion.ts",
  "desktop/src/onboarding/shutdown-coordination.ts",
  "desktop/src/runner-supervisor.ts",
  "desktop/src/settings-contract.ts",
  "desktop/src/status.ts",
  "desktop/src/team-conversation-preference-contract.ts",
  "desktop/src/team-execution-profile.ts",
  "desktop/src/team-external-change-contract.ts",
  "desktop/src/team-file-manager-contract.ts",
  "desktop/src/team-ipc-contract.ts",
  "desktop/src/team-model.ts",
  "desktop/src/team-repair-contract.ts",
  "src/agent-frontmatter.ts",
  "src/agent-manifest.ts",
  "src/agent-prescripts/types.ts",
  "src/claude-cli-version.ts",
  "src/codex-cli-version.ts",
  "src/conversation-interrupt.ts",
  "src/conversation.ts",
  "src/execution-contract.ts",
  "src/execution-profile-registry.ts",
  "src/github-response-intake.ts",
  "src/goal-ledger.ts",
  "src/issue-media.ts",
  "src/issue-source.ts",
  "src/local-console/control-dispatch.ts",
  "src/local-console/conversation-workspace-plan.ts",
  "src/local-console/canonical-json.ts",
  "src/local-console/child-session-summary.ts",
  "src/local-console/codex-thread-link.ts",
  "src/local-console/execution-context.ts",
  "src/local-console/member-identity.ts",
  "src/local-console/local-child-session-plan.ts",
  "src/local-console/orphan-runs.ts",
  "src/local-console/pending-session-context-plan.ts",
  "src/local-console/process-event-projector.ts",
  "src/local-console/provider-invocation-plan.ts",
  "src/local-console/project-command-plan.ts",
  "src/local-console/prompt.ts",
  "src/local-console/run-activity.ts",
  "src/local-console/run-failure-plan.ts",
  "src/local-console/run-invocation-plan.ts",
  "src/local-console/run-lifecycle-plan.ts",
  "src/local-console/run-recovery-plan.ts",
  "src/local-console/run-terminal-plan.ts",
  "src/local-console/runtime-domain.ts",
  "src/local-console/session-analysis-gate.ts",
  "src/local-console/session-continuation-plan.ts",
  "src/local-console/session-creation-plan.ts",
  "src/local-console/session-reference-text.ts",
  "src/local-console/session-reference-plan.ts",
  "src/local-console/session-presentation-plan.ts",
  "src/local-console/session-settings-plan.ts",
  "src/local-console/session-status.ts",
  "src/local-console/state-query-plan.ts",
  "src/local-console/session-fact-compaction.ts",
  "src/local-console/session-workspace-policy.ts",
  "src/local-console/timeline.ts",
  "src/local-console/title.ts",
  "src/local-console/types.ts",
  "src/local-console/user-message-routing.ts",
  "src/local-console/workspace-resolution.ts",
  "src/log.ts",
  "src/observer/model.ts",
  "src/run-supervisor.ts",
  "src/runtime-mode.ts",
  "src/session-key.ts",
  "src/stages.ts",
  "src/triggers/index.ts",
  "src/triggers/mention-trigger.ts",
  "src/triggers/types.ts",
] as const;

export const FOUR_LAYER_CONFIG: FourLayerArchitectureConfig = {
  assignments: [
    ...exact("view", FOUR_LAYER_VIEW_FILES),
    ...exact("application", FOUR_LAYER_APPLICATION_FILES),
    ...exact("adapter", FOUR_LAYER_ADAPTER_FILES),
    ...exact("domain", FOUR_LAYER_DOMAIN_FILES),
  ],
  compositionRoots: [
    "desktop/src/ai-team-builder/index.ts",
    "desktop/src/console-page/app.tsx",
    "desktop/src/main.ts",
    "desktop/src/onboarding/onboarding-route.tsx",
    "desktop/src/runner-child.ts",
    "src/local-console/runtime.ts",
    "src/local-console/run-lifecycle-runtime.ts",
    "src/runner.ts",
  ],
  dependencyDebt: [
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/ai-team-builder-ipc.ts", target: "desktop/src/ai-team-builder/index.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/ai-team-builder/team-writer.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "desktop/src/console-page/right-sidebar-tabs-store.ts", target: "packages/console-ui/src/console/right-sidebar-tabs.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "desktop/src/console-page/state-sync.ts", target: "desktop/src/console-page/browser-fetch.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "application-no-view-dependency", importer: "desktop/src/console-page/state-sync.ts", target: "packages/console-ui/src/index.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "desktop/src/console-page/use-managed-attachments.ts", target: "desktop/src/console-page/attachment-client.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/onboarding/ipc.ts", target: "desktop/src/ai-team-builder/index.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/team-ipc.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "desktop/src/team-onboarding-orchestration.ts", target: "node:fs/promises", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/team-record-store.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/team-store.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/ceo-ledger-context.ts", target: "src/ceo-scripts.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/ceo-ledger-context.ts", target: "src/config.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/ceo-ledger-context.ts", target: "src/goal-ledger-state.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/dev-workspace.ts", target: "node:child_process", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/dev-workspace.ts", target: "node:fs/promises", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/dev-workspace.ts", target: "src/agent-context-state.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/issue-worktree.ts", target: "node:child_process", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/issue-worktree.ts", target: "node:fs/promises", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/issue-worktree.ts", target: "src/agent-context-state.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/agent-prescripts/issue-worktree.ts", target: "src/config.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/ceo-orchestration.ts", target: "src/ceo-scripts.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "adapter-no-use-case-reentry", importer: "src/github.ts", target: "src/retry.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/local-console/process-history.ts", target: "src/local-console/codex-rollout.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/local-console/process-history.ts", target: "src/local-console/provider-process-trace.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/local-console/process-history.ts", target: "src/trusted-jsonl.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/local-console/route-bus.ts", target: "src/format-ceo.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-no-use-case-reentry", importer: "src/local-console/server.ts", target: "src/local-console/process-history.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-no-use-case-reentry", importer: "src/local-console/server.ts", target: "src/local-console/runtime.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/observer/server.ts", target: "src/observer/render.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/retry.ts", target: "src/config.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/runner/acceptance-prepass.ts", target: "src/config.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/runner/acceptance-prepass.ts", target: "src/format-ceo.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/runner/external-route.ts", target: "src/config.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/runner/external-route.ts", target: "src/format-ceo.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/runner/runtime-contracts.ts", target: "src/config.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "src/runner/runtime-contracts.ts", target: "src/format-ceo.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
  ],
  fileDebt: [
    { ruleId: "application-use-case-shape", file: "desktop/src/ai-team-builder/index.ts", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/console-page/app.tsx", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "application-use-case-shape", file: "desktop/src/main.ts", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/onboarding/onboarding-route.tsx", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "application-use-case-shape", file: "src/local-console/runtime.ts", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "application-use-case-shape", file: "src/runner.ts", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/claude-spawner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/codex-spawner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/kimi-spawner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/console-page/draft-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/console-page/right-sidebar-tabs-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/ipc.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-external-change.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-file-manager.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-management-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-record-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-repair-ipc.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-seed.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/ceo-scripts.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/claude.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/config.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/codex-resume.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/execution-driver.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/server.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/t5-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-boundary-branch-total", file: "src/observer/server.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/console-page/use-managed-attachments.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "application-use-case-shape", file: "desktop/src/runner-launch.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/agent-prescripts/ceo-ledger-context.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/agent-prescripts/current-repo-workspace.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/agent-prescripts/dev-workspace.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/agent-prescripts/index.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/agent-prescripts/issue-worktree.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/ceo-orchestration.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/driver-pool.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/issue-dispatcher.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/team-writer.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/console-page/settings-state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/console-page/team-state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-conversation-preference.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-ipc.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-official-management.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-official-update.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-runtime-binding.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/agent-context-state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/codex-rollout.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/codex.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/format-ceo.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/github-state-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/kimi.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "adapter-boundary-branch-total", file: "src/observer/read-state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/sqlite-state-worker.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/sqlite-state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/console-page/state-sync.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-20-desktop-renderer" },
    { ruleId: "application-use-case-shape", file: "src/local-console/process-history.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "application-use-case-shape", file: "src/local-console/route-bus.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-10-local-console" },
    { ruleId: "application-use-case-shape", file: "src/retry.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "src/runner/acceptance-prepass.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/runner/codex-execution-reaction.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/runner/external-route.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/runner/runtime-contracts.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/scanner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
    { ruleId: "application-use-case-shape", file: "src/state-persister.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-30-github-runner" },
  ],
  conditionPermits: [],
};
