import type { ArchitectureLayerAssignment, FourLayerArchitectureConfig } from "./import-boundaries.js";

const exact = (layer: ArchitectureLayerAssignment["layer"], paths: readonly string[]): ArchitectureLayerAssignment[] =>
  paths.map((value) => ({ layer, scope: { kind: "exact", value } }));

export const FOUR_LAYER_BOUNDARY_RULE_IDS = [
  "architecture-layer-assignment-total",
  "architecture-layer-dependency-matrix",
  "domain-pure-runtime-closure",
  "view-no-side-effect-adapters",
  "application-no-view-dependency",
  "adapter-no-use-case-reentry",
  "composition-root-narrow-allowlist",
  "application-use-case-shape",
  "adapter-boundary-branch-total",
] as const;

export const FOUR_LAYER_VIEW_FILES = [
  "packages/console-ui/src/ai-team-builder/team-builder-view.tsx",
  "packages/console-ui/src/ai-team-builder/team-proposal-card.tsx",
  "packages/console-ui/src/brand/moebius-logo.tsx",
  "packages/console-ui/src/console/accept-card.tsx",
  "packages/console-ui/src/console/agent-initial-avatar.tsx",
  "packages/console-ui/src/console/agent-markdown-mention-editor.tsx",
  "packages/console-ui/src/console/agent-message.tsx",
  "packages/console-ui/src/console/agent-team-detail.tsx",
  "packages/console-ui/src/console/agent-teams-page.tsx",
  "packages/console-ui/src/console/analysis-panel.tsx",
  "packages/console-ui/src/console/change-tab.tsx",
  "packages/console-ui/src/console/composer-context.tsx",
  "packages/console-ui/src/console/conversation-empty-state.tsx",
  "packages/console-ui/src/console/conversation-layout.ts",
  "packages/console-ui/src/console/conversation-relay-rail-model.ts",
  "packages/console-ui/src/console/conversation-relay-rail.tsx",
  "packages/console-ui/src/console/conversation-search.tsx",
  "packages/console-ui/src/console/conversation-sidebar.tsx",
  "packages/console-ui/src/console/execution-profile-registry.ts",
  "packages/console-ui/src/console/file-diff-view.tsx",
  "packages/console-ui/src/console/file-reference-tab.tsx",
  "packages/console-ui/src/console/markdown-internal-reference.ts",
  "packages/console-ui/src/console/markdown-message.tsx",
  "packages/console-ui/src/console/member-name.ts",
  "packages/console-ui/src/console/new-conversation-page.tsx",
  "packages/console-ui/src/console/operator-console.tsx",
  "packages/console-ui/src/console/process-event.tsx",
  "packages/console-ui/src/console/process-scroll-model.ts",
  "packages/console-ui/src/console/process-tab.tsx",
  "packages/console-ui/src/console/project-files-tab.tsx",
  "packages/console-ui/src/console/result-card.tsx",
  "packages/console-ui/src/console/right-sidebar-tabs.ts",
  "packages/console-ui/src/console/right-sidebar.tsx",
  "packages/console-ui/src/console/role-composer.tsx",
  "packages/console-ui/src/console/role-tag.tsx",
  "packages/console-ui/src/console/run-block.tsx",
  "packages/console-ui/src/console/run-outcome.tsx",
  "packages/console-ui/src/console/run-time.tsx",
  "packages/console-ui/src/console/session-context-header.tsx",
  "packages/console-ui/src/console/session-team-menu.tsx",
  "packages/console-ui/src/console/settings-dialog.tsx",
  "packages/console-ui/src/console/status-dot.ts",
  "packages/console-ui/src/console/structured-attachments.tsx",
  "packages/console-ui/src/console/sub-session-card.tsx",
  "packages/console-ui/src/console/sub-session-panel.tsx",
  "packages/console-ui/src/console/subtask-tab.tsx",
  "packages/console-ui/src/console/team-selection-label.ts",
  "packages/console-ui/src/console/text-fragment-list.tsx",
  "packages/console-ui/src/i18n/index.tsx",
  "packages/console-ui/src/i18n/locales/console.en.ts",
  "packages/console-ui/src/i18n/locales/console.zh-CN.ts",
  "packages/console-ui/src/i18n/locales/en.ts",
  "packages/console-ui/src/i18n/locales/zh-CN.ts",
  "packages/console-ui/src/i18n/resources.ts",
  "packages/console-ui/src/index.ts",
  "packages/console-ui/src/lib/utils.ts",
  "packages/console-ui/src/onboarding/onboarding-shell.tsx",
  "packages/console-ui/src/onboarding/onboarding-state.ts",
  "packages/console-ui/src/onboarding/relay-demo/relay-demo.tsx",
  "packages/console-ui/src/onboarding/relay-demo/relay-geometry.ts",
  "packages/console-ui/src/onboarding/relay-demo/relay-graph.tsx",
  "packages/console-ui/src/onboarding/relay-demo/relay-messages.tsx",
  "packages/console-ui/src/onboarding/relay-demo/relay-motion.ts",
  "packages/console-ui/src/onboarding/relay-demo/relay-replay-button.tsx",
  "packages/console-ui/src/style-entry.ts",
  "packages/console-ui/src/ui/avatar.tsx",
  "packages/console-ui/src/ui/badge.tsx",
  "packages/console-ui/src/ui/button.tsx",
  "packages/console-ui/src/ui/card.tsx",
  "packages/console-ui/src/ui/dropdown-menu.tsx",
  "packages/console-ui/src/ui/input.tsx",
  "packages/console-ui/src/ui/popover.tsx",
  "packages/console-ui/src/ui/tooltip.tsx",
  "desktop/src/console-page/conversation-search-overlay.tsx",
  "desktop/src/console-page/mount-console-app.tsx",
  "desktop/src/console-page/operator-console-view.tsx",
  "desktop/src/console-page/sidebar-conversation-view.tsx",
] as const;

export const FOUR_LAYER_APPLICATION_FILES = [
  "desktop/src/ai-team-builder/index.ts",
  "desktop/src/console-page/app.tsx",
  "desktop/src/console-page/desktop-application-root.tsx",
  "desktop/src/console-page/desktop-routes-controller.tsx",
  "desktop/src/console-page/operator-console-route.tsx",
  "desktop/src/console-page/console-state-actions.ts",
  "desktop/src/console-page/conversation-actions.ts",
  "desktop/src/console-page/load-evidence-view.ts",
  "desktop/src/console-page/load-conversation-analysis-target.ts",
  "desktop/src/console-page/load-previous-process-output.ts",
  "desktop/src/console-page/project-opening-actions.ts",
  "desktop/src/console-page/project-session-actions.ts",
  "desktop/src/console-page/use-project-mutations.ts",
  "desktop/src/console-page/use-project-file-reader.ts",
  "desktop/src/console-page/use-session-run-actions.ts",
  "desktop/src/console-page/use-session-console.ts",
  "desktop/src/console-page/use-sidebar-message-actions.ts",
  "desktop/src/console-page/use-sidebar-draft-actions.ts",
  "desktop/src/console-page/use-sidebar-draft-close.ts",
  "desktop/src/console-page/use-session-mutation-intents.ts",
  "desktop/src/console-page/refresh-console-state.ts",
  "desktop/src/console-page/selection-mutation-lifecycle.ts",
  "desktop/src/console-page/session-creation-actions.ts",
  "desktop/src/console-page/settings-request-controller.ts",
  "desktop/src/console-page/team-save-controller.ts",
  "desktop/src/console-page/use-desktop-settings.ts",
  "desktop/src/console-page/use-desktop-console-shell.ts",
  "desktop/src/console-page/use-desktop-runtime-bridge.ts",
  "desktop/src/console-page/use-desktop-shell-actions.ts",
  "desktop/src/console-page/use-edit-resend.ts",
  "desktop/src/console-page/use-active-cli-installations.ts",
  "desktop/src/console-page/use-analysis-panel-navigation.ts",
  "desktop/src/console-page/use-agent-team-builder.ts",
  "desktop/src/console-page/use-agent-team-builder-commands.ts",
  "desktop/src/console-page/use-agent-team-builder-finalization.ts",
  "desktop/src/console-page/use-agent-team-builder-session.ts",
  "desktop/src/console-page/use-agent-team-catalog.ts",
  "desktop/src/console-page/use-agent-team-console.ts",
  "desktop/src/console-page/use-agent-team-copy.ts",
  "desktop/src/console-page/use-agent-team-draft-state.ts",
  "desktop/src/console-page/use-agent-team-external-change.ts",
  "desktop/src/console-page/use-agent-team-member-editor.ts",
  "desktop/src/console-page/use-agent-team-member-loading.ts",
  "desktop/src/console-page/use-agent-team-member-mutations.ts",
  "desktop/src/console-page/use-agent-team-member-saving.ts",
  "desktop/src/console-page/use-agent-team-navigation.ts",
  "desktop/src/console-page/use-agent-team-record-mutations.ts",
  "desktop/src/console-page/use-agent-team-profile.ts",
  "desktop/src/console-page/use-agent-team-registration.ts",
  "desktop/src/console-page/use-desktop-language.ts",
  "desktop/src/console-page/use-managed-attachments.ts",
  "desktop/src/console-page/use-message-attachment-previews.ts",
  "desktop/src/console-page/use-new-conversation-submission.ts",
  "desktop/src/console-page/use-new-conversation-launcher.ts",
  "desktop/src/console-page/use-right-sidebar-console.ts",
  "desktop/src/console-page/use-right-sidebar-conversation-views.ts",
  "desktop/src/console-page/use-right-sidebar-process-data.ts",
  "desktop/src/console-page/use-right-sidebar-tabs.ts",
  "desktop/src/console-page/use-process-invocation-data.ts",
  "desktop/src/console-page/use-process-output-data.ts",
  "desktop/src/console-page/use-attachment-upload-queue.ts",
  "desktop/src/console-page/use-attachment-draft-actions.ts",
  "desktop/src/console-page/use-attachment-replacement.ts",
  "desktop/src/console-page/use-attachment-draft-restoration.ts",
  "desktop/src/console-page/use-attachment-preview-lifecycle.ts",
  "desktop/src/console-page/use-conversation-search.ts",
  "desktop/src/console-page/use-conversation-transition.ts",
  "desktop/src/console-page/use-console-attachment-drafts.ts",
  "desktop/src/console-page/use-console-state-sync.ts",
  "desktop/src/console-page/use-console-selection-state.ts",
  "desktop/src/console-page/use-console-local-state.ts",
  "desktop/src/console-page/use-console-state-actions.ts",
  "desktop/src/console-page/use-console-presentation.ts",
  "desktop/src/console-page/use-conversation-navigation.ts",
  "desktop/src/console-page/use-conversation-analysis.ts",
  "desktop/src/console-page/use-conversation-composer.ts",
  "desktop/src/console-page/use-conversation-console.ts",
  "desktop/src/console-page/use-searched-session-navigation.ts",
  "desktop/src/console-page/use-sidebar-source-migration.ts",
  "desktop/src/main.ts",
  "desktop/src/onboarding/onboarding-route.tsx",
  "desktop/src/onboarding/register.ts",
  "desktop/src/onboarding/use-onboarding-readiness.ts",
  "desktop/src/onboarding/use-onboarding-installation-actions.ts",
  "desktop/src/onboarding/use-onboarding-installation-state.ts",
  "desktop/src/onboarding/use-onboarding-installations.ts",
  "desktop/src/team-onboarding-orchestration.ts",
  "src/local-console/process-append-page-runtime.ts",
  "src/local-console/process-attempts-runtime.ts",
  "src/local-console/process-debug-invocation-runtime.ts",
  "src/local-console/process-history-page-runtime.ts",
  "src/local-console/process-history-output-runtime.ts",
  "src/local-console/process-link-runtime.ts",
  "src/local-console/conversation-workspace-runtime.ts",
  "src/local-console/message-command-runtime.ts",
  "src/local-console/message-retry-wiring.ts",
  "src/local-console/provider-invocation-flow.ts",
  "src/local-console/primary-preparation-runtime.ts",
  "src/local-console/primary-preparation-wiring.ts",
  "src/local-console/primary-provider-runtime.ts",
  "src/local-console/primary-provider-wiring.ts",
  "src/local-console/primary-analysis-runtime.ts",
  "src/local-console/primary-analysis-wiring.ts",
  "src/local-console/primary-dispatch-runtime.ts",
  "src/local-console/primary-dispatch-wiring.ts",
  "src/local-console/primary-execution-runtime.ts",
  "src/local-console/primary-execution-wiring.ts",
  "src/local-console/pending-processing-runtime.ts",
  "src/local-console/primary-terminal-runtime.ts",
  "src/local-console/primary-terminal-wiring.ts",
  "src/local-console/primary-wiring.ts",
  "src/local-console/route-bus.ts",
  "src/local-console/runtime.ts",
  "src/local-console/session-continuation-runtime.ts",
  "src/local-console/session-command-wiring.ts",
  "src/local-console/shared-run-wiring.ts",
  "src/local-console/session-metadata-runtime.ts",
  "src/local-console/session-metadata-wiring.ts",
  "src/local-console/session-presentation-runtime.ts",
  "src/local-console/state-query-runtime.ts",
  "src/local-console/run-preparation-flow.ts",
  "src/local-console/run-output-runtime.ts",
  "src/local-console/run-retry-runtime.ts",
  "src/local-console/runtime-facade.ts",
  "src/local-console/runtime-foundation-wiring.ts",
  "src/local-console/runtime-lifecycle-wiring.ts",
  "src/local-console/runtime-run-wiring.ts",
  "src/local-console/runtime-session-wiring.ts",
  "src/local-console/runtime-shutdown-runtime.ts",
  "src/local-console/runtime-wiring-context.ts",
  "src/local-console/run-failure-runtime.ts",
  "src/local-console/run-lifecycle-runtime.ts",
  "src/local-console/run-lifecycle-activity-runtime.ts",
  "src/local-console/run-lifecycle-record-runtime.ts",
  "src/local-console/pending-session-context-runtime.ts",
  "src/local-console/run-recovery-runtime.ts",
  "src/local-console/legacy-handoff-recovery-runtime.ts",
  "src/local-console/startup-recovery-runtime.ts",
  "src/local-console/startup-recovery-wiring.ts",
  "src/local-console/start.ts",
  "src/local-console/project-command-runtime.ts",
  "src/local-console/session-creation-runtime.ts",
  "src/local-console/session-settings-runtime.ts",
  "src/local-console/session-reference-runtime.ts",
  "src/local-console/session-read-wiring.ts",
  "src/local-console/run-terminal-flow.ts",
  "src/local-console/worker-dispatch-flow.ts",
  "src/local-console/worker-dispatch-runtime.ts",
  "src/local-console/worker-dispatch-wiring.ts",
  "src/local-console/worker-execution-runtime.ts",
  "src/local-console/worker-execution-wiring.ts",
  "src/local-console/worker-preparation-runtime.ts",
  "src/local-console/worker-preparation-wiring.ts",
  "src/local-console/worker-provider-runtime.ts",
  "src/local-console/worker-provider-wiring.ts",
  "src/local-console/worker-terminal-runtime.ts",
  "src/local-console/worker-terminal-wiring.ts",
  "src/local-console/worker-wiring.ts",
  "src/local-console/workspace-query-runtime.ts",
  "src/runner.ts",
] as const;

export const FOUR_LAYER_ADAPTER_FILES = [
  "desktop/src/ai-team-builder-ipc.ts",
  "desktop/src/ai-team-builder/claude-spawner.ts",
  "desktop/src/ai-team-builder/codex-spawner.ts",
  "desktop/src/ai-team-builder/kimi-spawner.ts",
  "desktop/src/ai-team-builder/team-writer.ts",
  "desktop/src/console-page/attachment-client.ts",
  "desktop/src/console-page/browser-fetch.ts",
  "desktop/src/console-page/console-api-client.ts",
  "desktop/src/console-page/console-command-client.ts",
  "desktop/src/console-page/conversation-search-browser-client.ts",
  "desktop/src/console-page/conversation-analysis-browser-port.ts",
  "desktop/src/console-page/conversation-view-browser-port.ts",
  "desktop/src/console-page/process-data-browser-port.ts",
  "desktop/src/console-page/project-mutation-browser-port.ts",
  "desktop/src/console-page/project-file-browser-port.ts",
  "desktop/src/console-page/session-run-browser-port.ts",
  "desktop/src/console-page/sidebar-message-browser-port.ts",
  "desktop/src/console-page/sidebar-draft-browser-port.ts",
  "desktop/src/console-page/searched-session-browser-port.ts",
  "desktop/src/console-page/console-state-sync-browser-port.ts",
  "desktop/src/console-page/draft-store.ts",
  "desktop/src/console-page/right-sidebar-tabs-store.ts",
  "desktop/src/data-root.ts",
  "desktop/src/ai-team-builder/execution-profile.ts",
  "desktop/src/env-doctor.ts",
  "desktop/src/execution-capabilities.ts",
  "desktop/src/external-link.ts",
  "desktop/src/language-preference-ipc.ts",
  "desktop/src/language-preference.ts",
  "desktop/src/main-window-options.ts",
  "desktop/src/onboarding/cli-installer-manager.ts",
  "desktop/src/onboarding/cli-installer-process.ts",
  "desktop/src/onboarding/first-run-marker.ts",
  "desktop/src/onboarding/cli-readiness.ts",
  "desktop/src/onboarding/ipc.ts",
  "desktop/src/preload.ts",
  "desktop/src/session-log-clipboard.ts",
  "desktop/src/settings-ipc.ts",
  "desktop/src/shell-path.ts",
  "desktop/src/team-conversation-preference.ts",
  "desktop/src/team-external-change.ts",
  "desktop/src/team-file-manager.ts",
  "desktop/src/team-ipc.ts",
  "desktop/src/team-management-store.ts",
  "desktop/src/team-official-management.ts",
  "desktop/src/team-official-update.ts",
  "desktop/src/team-record-store.ts",
  "desktop/src/team-repair-ipc.ts",
  "desktop/src/team-runtime-binding.ts",
  "desktop/src/team-seed.ts",
  "desktop/src/team-store.ts",
  "desktop/src/updater.ts",
  "src/ceo-scripts.ts",
  "src/claude-executable.ts",
  "src/claude.ts",
  "src/cli-executable.ts",
  "src/codex-rollout.ts",
  "src/codex.ts",
  "src/config.ts",
  "src/kimi-executable.ts",
  "src/kimi-runtime-home.ts",
  "src/kimi.ts",
  "src/local-config.ts",
  "src/local-console/attachments.ts",
  "src/local-console/child-session-summary-reader.ts",
  "src/local-console/codex-resume.ts",
  "src/local-console/codex-rollout.ts",
  "src/local-console/codex-thread-link-reader.ts",
  "src/local-console/execution-context-reader.ts",
  "src/local-console/execution-driver.ts",
  "src/local-console/file-read.ts",
  "src/local-console/local-route-adapter.ts",
  "src/local-console/local-route-persona.ts",
  "src/local-console/output-tail.ts",
  "src/local-console/process-fact-reader.ts",
  "src/local-console/provider-process-trace.ts",
  "src/local-console/run-recovery-reader.ts",
  "src/local-console/runtime-adapters.ts",
  "src/local-console/process-trace-reader.ts",
  "src/local-console/runtime-file-support.ts",
  "src/local-console/runtime-store-ports.ts",
  "src/local-console/server.ts",
  "src/local-console/session-fact-log.ts",
  "src/local-console/store.ts",
  "src/local-console/t5-store.ts",
  "src/local-console/store-timeout.ts",
  "src/local-console/workspace-diff.ts",
  "src/local-console/workspace-source.ts",
  "src/sqlite-state-worker.ts",
  "src/sqlite-state.ts",
  "src/trusted-jsonl.ts",
] as const;

export const FOUR_LAYER_DOMAIN_FILES = [
  "desktop/src/ai-team-builder/contract.ts",
  "desktop/src/ai-team-builder/driver.ts",
  "desktop/src/ai-team-builder/dto.ts",
  "desktop/src/ai-team-builder/instructions.ts",
  "desktop/src/ai-team-builder/output-schema.ts",
  "desktop/src/ai-team-builder/state-machine.ts",
  "desktop/src/ai-team-builder/validator.ts",
  "desktop/src/team-builder-view-state.ts",
  "desktop/src/console-page/attachment-preview.ts",
  "desktop/src/console-page/conversation-draft-model.ts",
  "desktop/src/console-page/console-state-coordinator.ts",
  "desktop/src/console-page/console-state-contract.ts",
  "desktop/src/console-page/console-state-sync-contract.ts",
  "desktop/src/console-page/console-state-action-contract.ts",
  "desktop/src/console-page/console-process-model.ts",
  "desktop/src/console-page/console-presentation-model.ts",
  "desktop/src/console-page/conversation-search-model.ts",
  "desktop/src/console-page/conversation-view-sync-contract.ts",
  "desktop/src/console-page/process-data-sync-contract.ts",
  "desktop/src/console-page/project-mutation-contract.ts",
  "desktop/src/console-page/project-mutation-model.ts",
  "desktop/src/console-page/project-file-contract.ts",
  "desktop/src/console-page/project-file-model.ts",
  "desktop/src/console-page/session-run-contract.ts",
  "desktop/src/console-page/session-run-model.ts",
  "desktop/src/console-page/sidebar-message-contract.ts",
  "desktop/src/console-page/sidebar-message-model.ts",
  "desktop/src/console-page/sidebar-draft-contract.ts",
  "desktop/src/console-page/sidebar-draft-model.ts",
  "desktop/src/console-page/searched-session-contract.ts",
  "desktop/src/console-page/searched-session-model.ts",
  "desktop/src/console-page/sidebar-source-migration-model.ts",
  "desktop/src/console-page/conversation-navigation-model.ts",
  "desktop/src/console-page/conversation-analysis-contract.ts",
  "desktop/src/console-page/conversation-analysis-model.ts",
  "desktop/src/console-page/agent-team-console-model.ts",
  "desktop/src/console-page/console-default-state.ts",
  "desktop/src/console-page/desktop-routing-model.ts",
  "desktop/src/console-page/desktop-api-contract.ts",
  "desktop/src/console-page/desktop-runtime-bridge-model.ts",
  "desktop/src/console-page/console-state-plan.ts",
  "desktop/src/console-page/conversation-reading-position.ts",
  "desktop/src/console-page/edit-resend.ts",
  "desktop/src/console-page/edit-resend-model.ts",
  "desktop/src/console-page/interrupt.ts",
  "desktop/src/console-page/language-state.ts",
  "desktop/src/console-page/managed-attachment-port.ts",
  "desktop/src/console-page/managed-attachment-model.ts",
  "desktop/src/console-page/managed-attachment-contract.ts",
  "desktop/src/console-page/new-conversation.ts",
  "desktop/src/console-page/new-conversation-launcher-model.ts",
  "desktop/src/console-page/presentation-route.ts",
  "desktop/src/console-page/process-output-locator.ts",
  "desktop/src/console-page/right-sidebar-preference.ts",
  "desktop/src/console-page/right-sidebar-tabs-model.ts",
  "desktop/src/onboarding/cli-installer-state.ts",
  "desktop/src/console-page/selection-preference.ts",
  "desktop/src/console-page/settings-state.ts",
  "desktop/src/console-page/team-state.ts",
  "desktop/src/console-page/sidebar-conversation-drafts.ts",
  "desktop/src/console-page/sidebar-conversation-view-model.ts",
  "desktop/src/console-page/session-mutation-model.ts",
  "desktop/src/console-page/sidebar-preference.ts",
  "desktop/src/i18n/index.ts",
  "desktop/src/i18n/locales/en.ts",
  "desktop/src/i18n/locales/zh-CN.ts",
  "desktop/src/language-preference-contract.ts",
  "desktop/src/onboarding/cli-installer-contract.ts",
  "desktop/src/onboarding/cli-installer-registry.ts",
  "desktop/src/onboarding/cli-readiness-contract.ts",
  "desktop/src/onboarding/contract.ts",
  "desktop/src/onboarding/onboarding-completion.ts",
  "desktop/src/onboarding/onboarding-installation-model.ts",
  "desktop/src/onboarding/onboarding-readiness-model.ts",
  "desktop/src/onboarding/shutdown-coordination.ts",
  "desktop/src/settings-contract.ts",
  "desktop/src/status.ts",
  "desktop/src/team-conversation-preference-contract.ts",
  "desktop/src/team-execution-profile.ts",
  "desktop/src/team-external-change-contract.ts",
  "desktop/src/team-file-manager-contract.ts",
  "desktop/src/team-ipc-contract.ts",
  "desktop/src/team-model.ts",
  "desktop/src/team-repair-contract.ts",
  "src/agent-frontmatter.ts",
  "src/agent-manifest.ts",
  "src/claude-cli-version.ts",
  "src/codex-cli-version.ts",
  "src/conversation.ts",
  "src/execution-contract.ts",
  "src/execution-profile-registry.ts",
  "src/goal-ledger.ts",
  "src/local-console/control-dispatch.ts",
  "src/local-console/agent-file.ts",
  "src/local-console/active-run.ts",
  "src/local-console/active-run-registry.ts",
  "src/local-console/conversation-workspace-plan.ts",
  "src/local-console/canonical-json.ts",
  "src/local-console/child-session-summary.ts",
  "src/local-console/codex-thread-link.ts",
  "src/local-console/ceo-orchestration-parser.ts",
  "src/local-console/execution-context.ts",
  "src/local-console/member-identity.ts",
  "src/local-console/message-command-plan.ts",
  "src/local-console/local-child-session-plan.ts",
  "src/local-console/orphan-runs.ts",
  "src/local-console/pending-session-context-plan.ts",
  "src/local-console/process-event-projector.ts",
  "src/local-console/provider-invocation-plan.ts",
  "src/local-console/primary-runtime-plan.ts",
  "src/local-console/pending-processing-plan.ts",
  "src/local-console/project-command-plan.ts",
  "src/local-console/prompt.ts",
  "src/local-console/run-activity.ts",
  "src/local-console/run-failure-plan.ts",
  "src/local-console/run-invocation-plan.ts",
  "src/local-console/run-lifecycle-plan.ts",
  "src/local-console/run-lifecycle-contracts.ts",
  "src/local-console/run-recovery-plan.ts",
  "src/local-console/startup-recovery-plan.ts",
  "src/local-console/run-terminal-plan.ts",
  "src/local-console/run-output-plan.ts",
  "src/local-console/run-retry-plan.ts",
  "src/local-console/runtime-domain.ts",
  "src/local-console/runtime-contracts.ts",
  "src/local-console/session-analysis-gate.ts",
  "src/local-console/process-history-contracts.ts",
  "src/local-console/process-history.ts",
  "src/local-console/local-route-plan.ts",
  "src/local-console/local-route-judgment.ts",
  "src/local-console/session-continuation-plan.ts",
  "src/local-console/session-creation-plan.ts",
  "src/local-console/session-metadata-plan.ts",
  "src/local-console/session-reference-text.ts",
  "src/local-console/session-reference-plan.ts",
  "src/local-console/session-presentation-plan.ts",
  "src/local-console/session-settings-plan.ts",
  "src/local-console/session-status.ts",
  "src/local-console/state-query-plan.ts",
  "src/local-console/session-fact-compaction.ts",
  "src/local-console/session-workspace-policy.ts",
  "src/local-console/timeline.ts",
  "src/local-console/title.ts",
  "src/local-console/types.ts",
  "src/local-console/user-message-routing.ts",
  "src/local-console/workspace-resolution.ts",
  "src/local-console/workspace-query-plan.ts",
  "src/local-console/worker-runtime-plan.ts",
  "src/log.ts",
  "src/run-supervisor.ts",
  "src/session-key.ts",
  "src/stages.ts",
  "src/triggers/index.ts",
  "src/triggers/mention-trigger.ts",
  "src/triggers/types.ts",
] as const;

export const FOUR_LAYER_CONFIG: FourLayerArchitectureConfig = {
  assignments: [
    ...exact("view", FOUR_LAYER_VIEW_FILES),
    ...exact("application", FOUR_LAYER_APPLICATION_FILES),
    ...exact("adapter", FOUR_LAYER_ADAPTER_FILES),
    ...exact("domain", FOUR_LAYER_DOMAIN_FILES),
  ],
  compositionRoots: [
    "desktop/src/ai-team-builder/index.ts",
    "desktop/src/console-page/app.tsx",
    "desktop/src/console-page/desktop-application-root.tsx",
    "desktop/src/main.ts",
    "desktop/src/onboarding/onboarding-route.tsx",
    "desktop/src/onboarding/register.ts",
    "src/local-console/runtime.ts",
    "src/local-console/start.ts",
    "src/runner.ts",
  ],
  dependencyDebt: [
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/ai-team-builder-ipc.ts", target: "desktop/src/ai-team-builder/index.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/ai-team-builder/team-writer.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/team-ipc.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "architecture-layer-dependency-matrix", importer: "desktop/src/team-onboarding-orchestration.ts", target: "node:fs/promises", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/team-record-store.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-no-use-case-reentry", importer: "desktop/src/team-store.ts", target: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer dependency frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
  ],
  fileDebt: [
    { ruleId: "application-use-case-shape", file: "desktop/src/ai-team-builder/index.ts", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/main.ts", reason: "pre-four-layer composition root exceeds narrow baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/claude-spawner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/codex-spawner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/kimi-spawner.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-external-change.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-file-manager.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-management-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-record-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-repair-ipc.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-seed.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/ceo-scripts.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/claude.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/config.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "application-use-case-shape", file: "desktop/src/team-onboarding-orchestration.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/ai-team-builder/team-writer.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-conversation-preference.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-ipc.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-official-management.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-official-update.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-runtime-binding.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/team-store.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/codex-rollout.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/codex.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/kimi.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/sqlite-state-worker.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
    { ruleId: "adapter-boundary-branch-total", file: "src/sqlite-state.ts", reason: "pre-four-layer branch/use-case shape frozen at 00 baseline", removalChange: "four-layer-40-adapter-convergence" },
  ],
  conditionPermits: [
    { ruleId: "application-use-case-shape", file: "desktop/src/console-page/use-desktop-settings.ts", exportName: "useDesktopSettingsBundle", fingerprint: "active", kind: "transport-control", contract: "unmounted renderer ignores a late application-info response" },
    { ruleId: "application-use-case-shape", file: "desktop/src/console-page/use-active-cli-installations.ts", exportName: "useActiveCliInstallationsBundle", fingerprint: "cancelled", kind: "transport-control", contract: "replaced renderer subscription ignores late installation events" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "startTrusted", fingerprint: "!task.settled", kind: "transport-control", contract: "heartbeat publishes only while the child-process task remains active" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "execute", fingerprint: "installer.cli !== task.cli", kind: "external-contract", contract: "trusted installer registry result must retain the requested CLI identity" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "execute", fingerprint: "task.terminalIntent ?? \"failed\"", kind: "transport-control", contract: "child-process completion resolves to the requested terminal signal or safe failure" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "execute", fingerprint: "task.settled", kind: "transport-control", contract: "late child-process rejection cannot settle an already completed task twice" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "execute", fingerprint: "task.children.size === 0", kind: "transport-control", contract: "terminal completion waits for every spawned process to close" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "stop", fingerprint: "task.children.size === 0", kind: "transport-control", contract: "a task without a live child settles without sending a process signal" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "stop", fingerprint: "task.children.size > 0 && !task.completionRejected", kind: "transport-control", contract: "bounded reap rejection applies only while an unreaped child remains" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "finish", fingerprint: "task.settled", kind: "transport-control", contract: "process task completion is idempotent" },
    { ruleId: "adapter-boundary-branch-total", file: "desktop/src/onboarding/cli-installer-manager.ts", exportName: "finish", fingerprint: "task.children.size !== 0", kind: "transport-control", contract: "successful settlement is forbidden until every child is reaped" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/codex-resume.ts", exportName: "readCompleteFactEvents", fingerprint: "!isRecord(value) || value.sessionId !== sessionId", kind: "external-contract", contract: "session fact envelope identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/codex-resume.ts", exportName: "parseResumeIntent", fingerprint: "!isRecord(value) || value.sessionId !== sessionId", kind: "external-contract", contract: "resume intent session identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/codex-resume.ts", exportName: "parseAgentHandoffRepairIntentId", fingerprint: "!isRecord(value) || value.sessionId !== sessionId", kind: "external-contract", contract: "handoff repair fact session identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/codex-resume.ts", exportName: "parseResumeConsumed", fingerprint: "!isRecord(value) || value.sessionId !== sessionId", kind: "external-contract", contract: "resume consumption session identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/execution-driver.ts", exportName: "observeSession", fingerprint: "options.mode.kind === \"resume\" && externalSessionId !== options.mode.externalSessionId", kind: "external-contract", contract: "provider resume session identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/execution-driver.ts", exportName: "markExecutionTraceReady", fingerprint: "observedExternalSessionId !== externalSessionId", kind: "external-contract", contract: "provider trace session identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/execution-driver.ts", exportName: "markExecutionTraceReady", fingerprint: "traceReadyExternalSessionId !== externalSessionId", kind: "external-contract", contract: "provider repeated trace identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/execution-driver.ts", exportName: "assertSuccessfulSessionIdentity", fingerprint: "mode.kind === \"resume\" && resultExternalSessionId !== mode.externalSessionId", kind: "external-contract", contract: "provider result resume identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveClaudeTrace", fingerprint: "!CLAUDE_SESSION_ID.test(link.externalSessionId)", kind: "external-contract", contract: "Claude session id format" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveClaudeTrace", fingerprint: "recordSessionId !== link.externalSessionId", kind: "external-contract", contract: "Claude transcript session identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveClaudeTrace", fingerprint: "malformedLines > 0 || !observedSession", kind: "external-contract", contract: "Claude transcript completeness" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveClaudeTrace", fingerprint: "malformedLines > 0 || !observedSession || !matchingCwd", kind: "external-contract", contract: "Claude transcript workspace identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveClaudeTrace", fingerprint: "malformedLines > 0 || !observedSession || !matchingCwd || mismatchedSession", kind: "external-contract", contract: "Claude transcript trusted identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveKimiTrace", fingerprint: "!KIMI_SESSION_ID.test(link.externalSessionId)", kind: "external-contract", contract: "Kimi session id format" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "resolveKimiTrace", fingerprint: "!isRecord(value) || value.sessionId !== link.externalSessionId", kind: "external-contract", contract: "Kimi session index identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "claudeContext", fingerprint: "message.role === \"user\"", kind: "external-contract", contract: "Claude transcript message role" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/provider-process-trace.ts", exportName: "claudeContext", fingerprint: "message.role === \"assistant\"", kind: "external-contract", contract: "Claude transcript message role" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordCodexThreadLink", fingerprint: "existing.threadId !== input.threadId || existing.sourceMessageId !== input.sourceMessageId || existing.role !== input.role", kind: "external-contract", contract: "Codex link immutable identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordCodexThreadLink", fingerprint: "existing.threadId !== input.threadId || existing.sourceMessageId !== input.sourceMessageId || existing.role !== input.role || existing.startedAt !== input.startedAt", kind: "external-contract", contract: "Codex link immutable timestamp" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordCodexThreadLink", fingerprint: "existing.threadId !== input.threadId || existing.sourceMessageId !== input.sourceMessageId || existing.role !== input.role || existing.startedAt !== input.startedAt || (existing.contextFingerprint ?? null) !== (input.contextFingerprint ?? null)", kind: "external-contract", contract: "Codex link immutable context" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordAgentSessionLink", fingerprint: "existing.externalSessionId !== input.externalSessionId || existing.role !== input.role", kind: "external-contract", contract: "Agent link immutable identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordAgentSessionLink", fingerprint: "existing.externalSessionId !== input.externalSessionId || existing.role !== input.role || existing.engine !== input.engine", kind: "external-contract", contract: "Agent link immutable engine" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordAgentSessionLink", fingerprint: "existing.externalSessionId !== input.externalSessionId || existing.role !== input.role || existing.engine !== input.engine || existing.profileFingerprint !== input.profileFingerprint", kind: "external-contract", contract: "Agent link immutable profile" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "recordAgentSessionLink", fingerprint: "existing.externalSessionId !== input.externalSessionId || existing.role !== input.role || existing.engine !== input.engine || existing.profileFingerprint !== input.profileFingerprint || existing.contextFingerprint !== input.contextFingerprint", kind: "external-contract", contract: "Agent link immutable context" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "appendIdempotentSessionFact", fingerprint: "event.payload.intentId === key || event.payload.runId === key || event.payload.agentIdentityFingerprint === key", kind: "external-contract", contract: "session fact idempotency key" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "buildFactEvent", fingerprint: "sessionId === command.parentSessionId", kind: "external-contract", contract: "child session fact projection" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "parseFactEvent", fingerprint: "!isRecord(value) || value.version !== 1 || value.sessionId !== sessionId", kind: "external-contract", contract: "session fact envelope identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/store.ts", exportName: "parseFactEvent", fingerprint: "!isLocalConsoleMessage(normalized) || normalized.sessionId !== sessionId", kind: "external-contract", contract: "session fact message identity" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/server.ts", exportName: "handleRequest", fingerprint: "!isRecord(payload) || !isStringArray(payload.projectIds)", kind: "external-contract", contract: "HTTP project reorder payload" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/server.ts", exportName: "handleRequest", fingerprint: "payload.agentTeamOwnership !== \"system\" && payload.agentTeamOwnership !== \"user\"", kind: "external-contract", contract: "HTTP team ownership payload" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/server.ts", exportName: "handleRequest", fingerprint: "!isRecord(payload) || (payload.agentTeamOwnership !== \"system\" && payload.agentTeamOwnership !== \"user\")", kind: "external-contract", contract: "HTTP team switch payload" },
    { ruleId: "adapter-boundary-branch-total", file: "src/local-console/server.ts", exportName: "readOptionalAgentTeam", fingerprint: "ownership !== \"system\" && ownership !== \"user\"", kind: "external-contract", contract: "HTTP optional team ownership" },
  ],
};
